type Query {
  getUser(id: String): Users
  getAll: [Users]
}
type Mutation {
  createUser(
    name: String
    email: String
    age: Int
    gender: String
    employment: Employment
    street: String
    city: String
    state: String
    country: String
  ): String
}
type Users {
  id: String
  name: String
  email: String
  age: Int
  gender: String
  address: Address
  employment: Employment
}
type Address {
  street: String
  city: String
  state: String
  country: String
}
enum Employment {
  SALARIED
  SELF_EMPLOYED
  GOVERNMENT_OFFICIAL
}
